-- ------------- INDUSTRIES -------------
INSERT INTO Industry (name, img, created_at, updated_at) VALUES ('Media','https://s-media-cache-ak0.pinimg.com/originals/30/dc/3a/30dc3afd1e8f395af2996217f1710bc9.jpg', 0, 0);
INSERT INTO Industry (name, img) VALUES ('Software','https://s-media-cache-ak0.pinimg.com/originals/30/dc/3a/30dc3afd1e8f395af2996217f1710bc9.jpg');
INSERT INTO Industry (name, img) VALUES ('Retail','https://s-media-cache-ak0.pinimg.com/originals/30/dc/3a/30dc3afd1e8f395af2996217f1710bc9.jpg');

--  ------------ USERS ------------

-- Applicant 1
-- Password knight
INSERT INTO User (name, username, email, password, img, is_employer, location, industry_id, info) VALUES ('Scarlet Knight', 'JerseyCoder','sknight@gmail.com', '$2a$10$TtXMHq5ZJVUeuASp/ZEReetxs1BdozCXv3Q/swYXOgWDJw6VnrY/O', 'http://www.motherearthnews.com/-/media/Images/MEN/Editorial/Articles/Magazine-Articles/2001/06-01/All-About-Raising-Llamas/Llama-jpg.jpg', false, 'New Jersey', 2,"User one public profile information blurb User one public profile information blurbUser one public profile information blurbUser one public profile information blurbUser one public profile information blurbUser one public profile information blurb");
INSERT INTO Conversation (is_anonymous, user_1, user_2, title) VALUES (false, 1, 2, "convo 1!");
INSERT INTO Message (subject, text, attachment, conversation_id, user_id) VALUES ('Message 1 Subject','Message 1 Text','Message 1 Attachment',1,1);
INSERT INTO Newsfeed (content, user_id) VALUES ('Content 1', 1);
INSERT INTO Credential (heading, subheading, details, section_name, user_id) VALUES ('S.B. in Chemical Engineering','Rutgers University','Relevant Courses: Chemistry, Engineering 101. GPA: 3.5. Tutor and undergraduate researcher', 'Education', 1);
INSERT INTO Credential (heading, subheading, details, section_name, user_id) VALUES ('Full Stack Coding Bootcamp','Rutgers','Knowledge of JavaScript, HTML, CSS, Bootstrap, MySQL and React.', 'Education', 1);
INSERT INTO Credential (heading, subheading, details, section_name, user_id) VALUES ('SAT Tutor','Kaplan','I tutor high school juniors for the SAT math exam.', 'Experience', 1);
INSERT INTO Credential (heading, subheading, details, section_name, user_id) VALUES ('Lab Technician','NJIT','I conduct chemistry experiments', 'Experience', 1);
INSERT INTO Credential (heading, subheading, details, section_name, user_id) VALUES ('The Acidity of Acids','Published in Science','Cited in a NYT pop science article: https://www.nytimes.com/ . Abstract: Lorem ipsum is an acid. Lorem ipsum is not a base. Lorem ipsum is an acid. Lorem ipsum is not a base. Lorem ipsum is an acid. Lorem ipsum is not a base. ', 'Accomplishments', 1);
INSERT INTO Credential (heading, subheading, details, section_name, user_id) VALUES ('Chemistry Club President','Rutgers University','4 year member and 2 year president of the Rugters Chemistry Club.', 'Leadership', 1);

-- ------------- EMPLOYERS ---------------

-- Employer 1 
INSERT INTO User (name, username, email, password, img, is_employer, location, industry_id, info) VALUES ('Alisa Media', 'MediaCo','Media@gmail.com', '$2a$10$BqyTSOHIrsLjDOY9Bo9TMetmxveqeUnnCHifBTJP4etlM4SHvdC0S', 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSILcFz6Y_fnk_QiXss-ydysMMJq9QExhw3SfeY9FJ35TUGYGd-2g', true, 'Somerset, NJ', 1, "Media company short bio Media company short bio Media company short bio Media company short bioMedia company short bio Media company short bioMedia company short bio");
INSERT INTO Newsfeed (content, user_id) VALUES ('Content 2', 2);

-- Employer 2
INSERT INTO User (name, username, email, password, img, is_employer, location, industry_id, info) VALUES ('Gavin Belson', 'HooliCo','Gavin@hooli.com', '$2a$10$7OCsiUzhrDnWNhZ1z2S9muqnq7mpIqxVmczYKIAvlExhUCcLnYebi', 'https://vignette3.wikia.nocookie.net/silicon-valley/images/f/f0/Hooli.png/revision/latest?cb=20160811201728', true, 'Silicon Valley', 2, "Hooli company short bio Hooli company short bio Hooli company short bio Hooli company short bio Hooli company short bio Hooli company short bio Hooli company short bio");
INSERT INTO Conversation (is_anonymous, user_1, user_2, title) VALUES (false, 1, 2, "convo 2!");
INSERT INTO Message (subject, text, attachment, conversation_id, user_id, created_at) VALUES ('Message 2 Subject','Message 2sdfasdf Text','Message 2 Attachment',1,1,0);
INSERT INTO Message (subject, text, attachment, conversation_id, user_id, created_at) VALUES ('Message safdaf2 Subject','Message dsafsdf2 Text','Message 2 Attachment',1,1,1);
INSERT INTO Message (subject, text, attachment, conversation_id, user_id, created_at) VALUES ('Message 1 Subject','Message 1 Text','Message 1 Attachment',1,1,2);
INSERT INTO Message (subject, text, attachment, conversation_id, user_id) VALUES ('Message sadfasdf1 Subject','Message 1 Text','Message 1 Attachment',1,1);
INSERT INTO Message (subject, text, attachment, conversation_id, user_id, created_at) VALUES ('Message 2 Subject','Message 2 23432423423Text','Message 2 Attachment',1,2,4);
INSERT INTO Message (subject, text, attachment, conversation_id, user_id, created_at) VALUES ('Message asdfdsf2 Subject','Message 223423423 Text','Message 2 Attachment',1,2,5);
INSERT INTO Message (subject, text, attachment, conversation_id, user_id) VALUES ('Message 2 Subject','Message 2 Text','Message 2 Attachment',1,2);
INSERT INTO Message (subject, text, attachment, conversation_id, user_id) VALUES ('Message sadfsd2 Subject','Message 3242342 Text','Message 2 Attachment',1,2);
INSERT INTO Message (subject, text, attachment, conversation_id, user_id, created_at) VALUES ('Message 3 Subject','Message 3 Text','Message 3 Attachment',1,2, 9);
INSERT INTO Newsfeed (content, user_id) VALUES ('Content 3', 3);

-- Job Descriptions pulled from:  https://resources.workable.com/
-- Employer 3


INSERT INTO User (name, username, email, password, img, is_employer, location, industry_id, info) VALUES ('Erlich Bachman', 'PiedPiperCo','e@piedpiper.com', '$2a$10$qRtLMeamR87/z.GOd/ybvOKJnuKcVjrO.MoTqGCoTluKeawdT8U/2', 'https://res.cloudinary.com/crunchbase-production/image/upload/v1399404021/jszf5otv3hpaeakvub8z.png', true, 'Silicon Valley' , 2, "Short bio section about pied piper Short bio section about pied piper Short bio section about pied piper Short bio section about pied piper Short bio section about pied piper Short bio section about pied piper ");
INSERT INTO Conversation (is_anonymous) VALUES (false);
INSERT INTO Message (subject, text, attachment, conversation_id, user_id) VALUES ('Message 3 Subject','Message 3 Text','Message 3 Attachment',3,3);
INSERT INTO Newsfeed (content, user_id) VALUES ('Content 3', 3);


-- --------------- COMPANIES ---------------

INSERT INTO Company (name, industry_id, user_id) VALUES ('Media Company', 1, 2);
INSERT INTO Company (name, industry_id, user_id) VALUES ('Hooli', 2, 3);
INSERT INTO Company (name, industry_id, user_id) VALUES ('Pied Piper', 2, 4);

-- --------------- JOBS ---------------
INSERT INTO Job (title, location, description, responsibilities, qualifications, industry_id, company_id) VALUES ('Billing Coordinator','Piscataway','We are looking for a trustworthy Billing coordinator to ensure the company tracks and collects debts consistently and correctly. Your job will be important for safeguarding our revenues.', 'Collaborating with finance and sales professionals to maintain accounts receivable. Compiling and process information such as prices, discounts, shipping rates etc. Ensuring customers are billed correctly for services offered','Proven experience as billing coordinator or similar position. Understanding of relevant laws and best practices. Proficient in MS office and data entry; working knowledge of ERP software is a plus',3,3);
INSERT INTO Job (title, location, description, responsibilities, qualifications, industry_id, company_id) VALUES ('Senior Software Engineer','Somerset','We are looking for a Senior Software Engineer to produce and implement functional software solutions. You will work with upper management to define software requirements and take the lead on operational and technical projects.', 'Directing software development projects. Producing, testing and debugging code. Leading engineers and developers','Extensive experience in software development, scripting and project management. Experience using system monitoring tools (e.g. New Relic) and automated testing frameworks. Knowledge of selected programming languages (e.g. Python, C++) and the Java/J2EE platform. In-depth knowledge of relational databases (e.g. PostgreSQL, MySQL) and NoSQL databases (e.g. MongoDB)',2,2);
INSERT INTO Job (title, location, description, responsibilities, qualifications, industry_id, company_id) VALUES ('Junior Software Engineer','Somerset','We are looking for a Junior Software Engineer to produce and implement functional software solutions.', 'Producing, testing and debugging code.','Some experience in software development and scripting. Graphic design a plus. Knowledge of Javscript and frameworks. Knowledge of relational databases (e.g. PostgreSQL, MySQL) and NoSQL databases (e.g. MongoDB) a plus.',2,2);
INSERT INTO Job (title, location, description, responsibilities, qualifications, industry_id, company_id) VALUES ('Web Editor','New Brunswick','We are looking for a passionate web editor to research, plan, write and edit web content. The successful candidate should be a skilled writer and researcher, with an eye for detail and an understanding of the special requirements of web writing. The goal is to produce creative web content to appeal to our audience.', 'Producing and publishing new content in a creative way. Liaising with clients and in-house team members to decide on new posts. Overseeing layout (images, graphics, videos and artwork)','Proven work experience as a web editor. Editing skills with a demonstrable portfolio of published work. Hands on experience with MS Office, InDesign, Photoshop or other publishing tools. In-depth knowledge of SEO',1,1);





INSERT INTO Industry (name, img) VALUES ('Media','https://s-media-cache-ak0.pinimg.com/originals/30/dc/3a/30dc3afd1e8f395af2996217f1710bc9.jpg');
INSERT INTO Industry (name, img) VALUES ('Software','https://s-media-cache-ak0.pinimg.com/originals/30/dc/3a/30dc3afd1e8f395af2996217f1710bc9.jpg');
INSERT INTO Industry (name, img) VALUES ('Retail','https://s-media-cache-ak0.pinimg.com/originals/30/dc/3a/30dc3afd1e8f395af2996217f1710bc9.jpg');

INSERT INTO User (name, username, email, password, img, is_employer, location, industry_id, info) VALUES ('Scarlet Knight', 'JerseyCoder','sknight@gmail.com', '$2a$10$TtXMHq5ZJVUeuASp/ZEReetxs1BdozCXv3Q/swYXOgWDJw6VnrY/O', 'http://grfx.cstv.com/schools/rutu/graphics/tradition/images/knight.jpg', false, 'New Jersey', 2,"User one public profile information blurb User one public profile information blurbUser one public profile information blurbUser one public profile information blurbUser one public profile information blurbUser one public profile information blurb");


INSERT INTO Credential (heading, subheading, details, section_name, user_id) VALUES ('S.B. in Chemical Engineering','Rutgers University','Relevant Courses: Chemistry, Engineering 101. GPA: 3.5. Tutor and undergraduate researcher', 'Education', 1);
INSERT INTO Credential (heading, subheading, details, section_name, user_id) VALUES ('Full Stack Coding Bootcamp','Rutgers','Knowledge of JavaScript, HTML, CSS, Bootstrap, MySQL and React.', 'Education', 1);
INSERT INTO Credential (heading, subheading, details, section_name, user_id) VALUES ('SAT Tutor','Kaplan','I tutor high school juniors for the SAT math exam.', 'Experience', 1);
INSERT INTO Credential (heading, subheading, details, section_name, user_id) VALUES ('Lab Technician','NJIT','I conduct chemistry experiments', 'Experience', 1);
INSERT INTO Credential (heading, subheading, details, section_name, user_id) VALUES ('The Acidity of Acids','Published in Science','Cited in a NYT pop science article: https://www.nytimes.com/ . Abstract: Lorem ipsum is an acid. Lorem ipsum is not a base. Lorem ipsum is an acid. Lorem ipsum is not a base. Lorem ipsum is an acid. Lorem ipsum is not a base. ', 'Accomplishments', 1);
INSERT INTO Credential (heading, subheading, details, section_name, user_id) VALUES ('Chemistry Club President','Rutgers University','4 year member and 2 year president of the Rugters Chemistry Club.', 'Leadership', 1);

INSERT INTO User (name, username, email, password, img, is_employer, location, industry_id, info) VALUES ('Alisa Media', 'Media Company','Media@gmail.com', '$2a$10$BqyTSOHIrsLjDOY9Bo9TMetmxveqeUnnCHifBTJP4etlM4SHvdC0S', 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSILcFz6Y_fnk_QiXss-ydysMMJq9QExhw3SfeY9FJ35TUGYGd-2g', true, 'Somerset, NJ', 1, "Media Company is an American commercial broadcast television network that is a flagship property of MediaUniversal, a subsidiary of Comcast. The network is headquartered in the Comcast Building (formerly known as the GE Building) at Rockefeller Center in New York City, with additional major offices near Los Angeles (at Universal City Plaza), Chicago (at the NBC Tower) and soon in Philadelphia at Comcast Innovation and Technology Center. The network is part of the Big Three television networks. Media is sometimes referred to as the 'megaphone network', in reference to its stylized logo, which was originally created in 1956 for its then-new color broadcasts and became the network's official emblem in 1979.");
INSERT INTO User (name, username, email, password, img, is_employer, location, industry_id, info) VALUES ('Gavin Belson', 'Hooli','Gavin@hooli.com', '$2a$10$7OCsiUzhrDnWNhZ1z2S9muqnq7mpIqxVmczYKIAvlExhUCcLnYebi', 'https://vignette3.wikia.nocookie.net/silicon-valley/images/f/f0/Hooli.png/revision/latest?cb=20160811201728', true, 'Silicon Valley', 2, "
We're bigger than our unrivaled Hooli cloud computing services.
Our products are more than hardware or software.	

We are more than just APIs, NFC, IDEs, SDKs, PPIs...FYI.

Hooli isn't just about software, Hooli is about people.

We hope people will see beyond our core competencies—we are so much more.

Our offerings don't stop at our visionary diversity, societal contributions or unwavering commitment to social justice.

Our employees derive satisfaction from more than just our state-of the-art facilities and pressworthy benefits.	

We do more than break down walls.

Hooli isn't just changing Silicon Valley... we're changing the world.

We're bigger than our innovations.

We're more than the sum of our collective accolades. We're not just a tech company. We're... Hooli. 	  
");


INSERT INTO User (name, username, email, password, img, is_employer, location, industry_id, info) VALUES ('Erlich Bachman', 'Pied PiperCo','e@piedpiper.com', '$2a$10$qRtLMeamR87/z.GOd/ybvOKJnuKcVjrO.MoTqGCoTluKeawdT8U/2', 'https://res.cloudinary.com/crunchbase-production/image/upload/v1399404021/jszf5otv3hpaeakvub8z.png', true, 'Silicon Valley' , 2, "Pied Piper is proud to introduce PiperChat, the world’s best video chat platform! With our revolutionary compression algorithm, your online conversations have never been clearer or faster. Whether you’re at work conferencing with colleagues or calling home from a double black in Tahoe, PiperChat connects.");
INSERT INTO Company (name, industry_id, user_id) VALUES ('Media Company', 1, 2);
INSERT INTO Company (name, industry_id, user_id) VALUES ('Hooli', 2, 3);
INSERT INTO Company (name, industry_id, user_id) VALUES ('Pied Piper', 2, 4);

INSERT INTO Job (title, location, description, responsibilities, qualifications, industry_id, company_id) VALUES ('Billing Coordinator','Piscataway','We are looking for a trustworthy Billing coordinator to ensure the company tracks and collects debts consistently and correctly. Your job will be important for safeguarding our revenues.', 'Collaborating with finance and sales professionals to maintain accounts receivable. Compiling and process information such as prices, discounts, shipping rates etc. Ensuring customers are billed correctly for services offered','Proven experience as billing coordinator or similar position. Understanding of relevant laws and best practices. Proficient in MS office and data entry; working knowledge of ERP software is a plus',3,3);
INSERT INTO Job (title, location, description, responsibilities, qualifications, industry_id, company_id) VALUES ('Manager','Newark','We are looking for a trustworthy Billing coordinator to ensure the company tracks and collects debts consistently and correctly. Your job will be important for safeguarding our revenues.', 'Collaborating with finance and sales professionals to maintain accounts receivable. Compiling and process information such as prices, discounts, shipping rates etc. Ensuring customers are billed correctly for services offered','Proven experience as billing coordinator or similar position. Understanding of relevant laws and best practices. Proficient in MS office and data entry; working knowledge of ERP software is a plus',3,3);
INSERT INTO Job (title, location, description, responsibilities, qualifications, industry_id, company_id) VALUES ('Accounts Manager','Jersey City','We are looking for a trustworthy Billing coordinator to ensure the company tracks and collects debts consistently and correctly. Your job will be important for safeguarding our revenues.', 'Collaborating with finance and sales professionals to maintain accounts receivable. Compiling and process information such as prices, discounts, shipping rates etc. Ensuring customers are billed correctly for services offered','Proven experience as billing coordinator or similar position. Understanding of relevant laws and best practices. Proficient in MS office and data entry; working knowledge of ERP software is a plus',3,3);
INSERT INTO Job (title, location, description, responsibilities, qualifications, industry_id, company_id) VALUES ('Senior Software Engineer','Somerset','We are looking for a Senior Software Engineer to produce and implement functional software solutions. You will work with upper management to define software requirements and take the lead on operational and technical projects.', 'Directing software development projects. Producing, testing and debugging code. Leading engineers and developers','Extensive experience in software development, scripting and project management. Experience using system monitoring tools (e.g. New Relic) and automated testing frameworks. Knowledge of selected programming languages (e.g. Python, C++) and the Java/J2EE platform. In-depth knowledge of relational databases (e.g. PostgreSQL, MySQL) and NoSQL databases (e.g. MongoDB)',2,2);
INSERT INTO Job (title, location, description, responsibilities, qualifications, industry_id, company_id) VALUES ('Junior Software Engineer','Somerset','We are looking for a Junior Software Engineer to produce and implement functional software solutions.', 'Producing, testing and debugging code.','Some experience in software development and scripting. Graphic design a plus. Knowledge of Javscript and frameworks. Knowledge of relational databases (e.g. PostgreSQL, MySQL) and NoSQL databases (e.g. MongoDB) a plus.',2,2);
INSERT INTO Job (title, location, description, responsibilities, qualifications, industry_id, company_id) VALUES ('Software Engineer','Somerset','We are looking for a Software Engineer to produce and implement functional software solutions.', 'Producing, testing and debugging code.','Some experience in software development and scripting. Graphic design a plus. Knowledge of Javscript and frameworks. Knowledge of relational databases (e.g. PostgreSQL, MySQL) and NoSQL databases (e.g. MongoDB) a plus.',2,2);
INSERT INTO Job (title, location, description, responsibilities, qualifications, industry_id, company_id) VALUES ('Junior Software Engineer','Somerset','We are looking for a Junior Software Engineer to produce and implement functional software solutions.', 'Producing, testing and debugging code.','Some experience in software development and scripting. Graphic design a plus. Knowledge of Javscript and frameworks. Knowledge of relational databases (e.g. PostgreSQL, MySQL) and NoSQL databases (e.g. MongoDB) a plus.',2,2);
INSERT INTO Job (title, location, description, responsibilities, qualifications, industry_id, company_id) VALUES ('Senior Software Engineer','Somerset','We are looking for a Senior Software Engineer to produce and implement functional software solutions.', 'Producing, testing and debugging code.','Some experience in software development and scripting. Graphic design a plus. Knowledge of Javscript and frameworks. Knowledge of relational databases (e.g. PostgreSQL, MySQL) and NoSQL databases (e.g. MongoDB) a plus.',2,2);
INSERT INTO Job (title, location, description, responsibilities, qualifications, industry_id, company_id) VALUES ('Junior Software Engineer','Somerset','We are looking for a Junior Software Engineer to produce and implement functional software solutions.', 'Producing, testing and debugging code.','Some experience in software development and scripting. Graphic design a plus. Knowledge of Javscript and frameworks. Knowledge of relational databases (e.g. PostgreSQL, MySQL) and NoSQL databases (e.g. MongoDB) a plus.',2,2);
INSERT INTO Job (title, location, description, responsibilities, qualifications, industry_id, company_id) VALUES ('Web Editor','New Brunswick','We are looking for a passionate web editor to research, plan, write and edit web content. The successful candidate should be a skilled writer and researcher, with an eye for detail and an understanding of the special requirements of web writing. The goal is to produce creative web content to appeal to our audience.', 'Producing and publishing new content in a creative way. Liaising with clients and in-house team members to decide on new posts. Overseeing layout (images, graphics, videos and artwork)','Proven work experience as a web editor. Editing skills with a demonstrable portfolio of published work. Hands on experience with MS Office, InDesign, Photoshop or other publishing tools. In-depth knowledge of SEO',1,1);
INSERT INTO Job (title, location, description, responsibilities, qualifications, industry_id, company_id) VALUES ('Web Editor','Somerset','We are looking for a passionate web editor to research, plan, write and edit web content. The successful candidate should be a skilled writer and researcher, with an eye for detail and an understanding of the special requirements of web writing. The goal is to produce creative web content to appeal to our audience.', 'Producing and publishing new content in a creative way. Liaising with clients and in-house team members to decide on new posts. Overseeing layout (images, graphics, videos and artwork)','Proven work experience as a web editor. Editing skills with a demonstrable portfolio of published work. Hands on experience with MS Office, InDesign, Photoshop or other publishing tools. In-depth knowledge of SEO',1,1);
INSERT INTO Job (title, location, description, responsibilities, qualifications, industry_id, company_id) VALUES ('Web Editor','Jersey City','We are looking for a passionate web editor to research, plan, write and edit web content. The successful candidate should be a skilled writer and researcher, with an eye for detail and an understanding of the special requirements of web writing. The goal is to produce creative web content to appeal to our audience.', 'Producing and publishing new content in a creative way. Liaising with clients and in-house team members to decide on new posts. Overseeing layout (images, graphics, videos and artwork)','Proven work experience as a web editor. Editing skills with a demonstrable portfolio of published work. Hands on experience with MS Office, InDesign, Photoshop or other publishing tools. In-depth knowledge of SEO',1,1);
INSERT INTO Job (title, location, description, responsibilities, qualifications, industry_id, company_id) VALUES ('Journalist','New Brunswick','We are looking for a passionate journalist to research, plan, write and edit web content. The successful candidate should be a skilled writer and researcher, with an eye for detail and an understanding of the special requirements of web writing. The goal is to produce creative web content to appeal to our audience.', 'Producing and publishing new content in a creative way. Liaising with clients and in-house team members to decide on new posts. Overseeing layout (images, graphics, videos and artwork)','Proven work experience as a web editor. Editing skills with a demonstrable portfolio of published work. Hands on experience with MS Office, InDesign, Photoshop or other publishing tools. In-depth knowledge of SEO',1,1);
INSERT INTO Job (title, location, description, responsibilities, qualifications, industry_id, company_id) VALUES ('Manager','Jersey City','We are looking for a passionate manager to research, plan, write and edit web content. The successful candidate should be a skilled writer and researcher, with an eye for detail and an understanding of the special requirements of web writing. The goal is to produce creative web content to appeal to our audience.', 'Producing and publishing new content in a creative way. Liaising with clients and in-house team members to decide on new posts. Overseeing layout (images, graphics, videos and artwork)','Proven work experience as a web editor. Editing skills with a demonstrable portfolio of published work. Hands on experience with MS Office, InDesign, Photoshop or other publishing tools. In-depth knowledge of SEO',1,1);



